services:
  backend:
    build:
      context: .
      dockerfile: src/main/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env

  frontend:
    build:
      context: ./src/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
