spring.application.name=devhub
spring.data.mongodb.uri=mongodb+srv://richardcastillo1236:pepeelmalo@fundamentosmongo.3njrzqk.mongodb.net/DevHubDB?retryWrites=true&w=majority
jwt.secret=rAZh5SYLNvlY7Z8c/WCFi8Z2oYznXFgdGe7UxMouISw=
spring.data.mongodb.database=DevHubDB
logging.level.org.springframework.data.mongodb=DEBUG