package com.skillstack.devhub.Controller;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/users")
public class UserController {
    //aqui se definen los endpoints para manejar las solicitudes relacionadas con los usuarios, 
    // como crear un usuario, listar usuarios, actualizar un usuario, eliminar un usuario, etc

}