name: Quality Metrics - Backend

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  quality-metrics:
    name: Generate Quality Metrics Reports
    runs-on: ubuntu-latest

    env:
          MONGOURI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS}}
          ADMIN_SECRET: ${{secrets.ADMIN_SECRET}}
          TWILIO_ACCOUNT_SID: ${{secrets.TWILIO_ACCOUNT_SID}}
          TWILIO_AUTH_TOKEN: ${{secrets.TWILIO_AUTH_TOKEN}}
          TWILIO_MESSAGING_SERVICE_SID: ${{secrets.TWILIO_MESSAGING_SERVICE_SID}}

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Verify Java Version
        run: java -version

      # Build
      - name: Build project
        run: mvn clean compile

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install javalang requests

      # METRICA 1
      # Cyclomatic Complexity
     
      - name: Generate PMD XML
        run: mvn pmd:pmd

      - name: Generate Cyclomatic HTML Report
        run: |
          python3 .github/scripts/cyclomatic_report.py

      # METRICA 2
      # Lines of Code
      
      - name: Generate LOC HTML Report
        run: |
          python3 .github/scripts/loc_report.py


      # METRICA 3
      # Nesting

      - name: Generate Nesting HTML Report
        run: |
          python3 .github/scripts/nesting_report.py


      #METRICA 4
      - name: Start backend
        run: |
          mvn spring-boot:run > spring.log 2>&1 &
          sleep 40

      
      - name: Latency Metric HTML Report
        run: |
          python3 .github/scripts/latency_report.py


      - name: Upload Quality Reports
        uses: actions/upload-artifact@v4
        with:
          name: quality-metrics-report
          path: target/quality-reports/
          retention-days: 30
      
      
      - name: Print Summary
        run: |
          echo "Quality metrics generated"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Reports:"
          ls -la target/quality-reports
